// Convert a GLB mesh into a 50k-point binary PLY, matching the format of the
// existing /clouds/*.ply files (trimesh-generated): binary_little_endian,
// element vertex 50000, float x/y/z + uchar r/g/b/a.
//
// Uses three.js — the same engine the atlas renderer is built on — via its
// GLTFLoader + MeshSurfaceSampler addons. Surface-area-weighted sampling, then
// normalised to the project convention: centred at origin, largest extent = 1.
//
// Usage: node scripts/glb-to-ply.mjs <input.glb> <output.ply>

import fs from 'node:fs';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { MeshSurfaceSampler } from 'three/addons/math/MeshSurfaceSampler.js';

const POINTS = 50000;

const [, , inPath, outPath] = process.argv;
if (!inPath || !outPath) {
  console.error('usage: node scripts/glb-to-ply.mjs <input.glb> <output.ply>');
  process.exit(1);
}

const buf = fs.readFileSync(inPath);
const arrayBuffer = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);

const loader = new GLTFLoader();

loader.parse(arrayBuffer, '', (gltf) => {
  // Collect all meshes, bake world transform into a merged-positions sampler.
  // These Meshy exports are single-mesh, but handle multi-mesh defensively by
  // sampling each in proportion to its surface area.
  const meshes = [];
  gltf.scene.updateMatrixWorld(true);
  gltf.scene.traverse((o) => { if (o.isMesh && o.geometry) meshes.push(o); });
  if (!meshes.length) { console.error('no meshes in', inPath); process.exit(1); }

  // Per-mesh: clone geometry, bake world matrix, build area-weighted sampler.
  const samplers = meshes.map((m) => {
    const g = m.geometry.clone();
    g.applyMatrix4(m.matrixWorld);
    // MeshSurfaceSampler needs non-indexed-friendly geometry; it handles
    // indexed geometry, but requires a position attribute only.
    const s = new MeshSurfaceSampler(new THREE.Mesh(g)).build();
    // Surface area for proportional allocation.
    g.computeBoundingBox();
    let area = 0;
    const pos = g.attributes.position;
    const idx = g.index;
    const a = new THREE.Vector3(), b = new THREE.Vector3(), c = new THREE.Vector3();
    const tri = new THREE.Triangle();
    const triCount = idx ? idx.count / 3 : pos.count / 3;
    for (let t = 0; t < triCount; t++) {
      const i0 = idx ? idx.getX(t * 3) : t * 3;
      const i1 = idx ? idx.getX(t * 3 + 1) : t * 3 + 1;
      const i2 = idx ? idx.getX(t * 3 + 2) : t * 3 + 2;
      a.fromBufferAttribute(pos, i0);
      b.fromBufferAttribute(pos, i1);
      c.fromBufferAttribute(pos, i2);
      tri.set(a, b, c);
      area += tri.getArea();
    }
    return { sampler: s, area };
  });

  const totalArea = samplers.reduce((s, x) => s + x.area, 0) || 1;

  // Sample points.
  const xyz = new Float32Array(POINTS * 3);
  const p = new THREE.Vector3();
  let written = 0;
  for (let si = 0; si < samplers.length; si++) {
    const isLast = si === samplers.length - 1;
    const want = isLast ? POINTS - written : Math.round((samplers[si].area / totalArea) * POINTS);
    for (let i = 0; i < want && written < POINTS; i++) {
      samplers[si].sampler.sample(p);
      xyz[written * 3] = p.x;
      xyz[written * 3 + 1] = p.y;
      xyz[written * 3 + 2] = p.z;
      written++;
    }
  }

  // Normalise: centre at bbox centre, scale so largest extent = 1.0.
  let mn = [Infinity, Infinity, Infinity], mx = [-Infinity, -Infinity, -Infinity];
  for (let i = 0; i < POINTS; i++) {
    for (let k = 0; k < 3; k++) {
      const v = xyz[i * 3 + k];
      if (v < mn[k]) mn[k] = v;
      if (v > mx[k]) mx[k] = v;
    }
  }
  const ctr = mn.map((m, k) => (m + mx[k]) / 2);
  const maxExtent = Math.max(mx[0] - mn[0], mx[1] - mn[1], mx[2] - mn[2]) || 1;
  const scale = 1 / maxExtent;
  for (let i = 0; i < POINTS; i++) {
    for (let k = 0; k < 3; k++) {
      xyz[i * 3 + k] = (xyz[i * 3 + k] - ctr[k]) * scale;
    }
  }

  // Write binary PLY: 12 bytes xyz float + 4 bytes rgba uchar per vertex.
  const header =
    'ply\n' +
    'format binary_little_endian 1.0\n' +
    'comment generated by scripts/glb-to-ply.mjs (three.js MeshSurfaceSampler)\n' +
    `element vertex ${POINTS}\n` +
    'property float x\nproperty float y\nproperty float z\n' +
    'property uchar red\nproperty uchar green\nproperty uchar blue\nproperty uchar alpha\n' +
    'end_header\n';
  const headerBuf = Buffer.from(header, 'latin1');
  const body = Buffer.alloc(POINTS * 16);
  for (let i = 0; i < POINTS; i++) {
    const o = i * 16;
    body.writeFloatLE(xyz[i * 3], o);
    body.writeFloatLE(xyz[i * 3 + 1], o + 4);
    body.writeFloatLE(xyz[i * 3 + 2], o + 8);
    body[o + 12] = 255; body[o + 13] = 255; body[o + 14] = 255; body[o + 15] = 255;
  }
  fs.writeFileSync(outPath, Buffer.concat([headerBuf, body]));
  console.log(`${inPath} -> ${outPath}  (${POINTS} pts, extent ${maxExtent.toFixed(3)})`);
}, (err) => {
  console.error('GLTF parse failed for', inPath, err);
  process.exit(1);
});
