// Bake a point-cloud GLOBE: sample 50k points that fall on land and project
// them onto a unit sphere, writing a binary PLY in the exact format the atlas
// renderer expects (see scripts/glb-to-ply.mjs): binary_little_endian,
// element vertex 50000, float x/y/z + uchar r/g/b/a (white; the renderer
// colours by depth, not by the stored colour).
//
// Unlike glb-to-ply.mjs (which samples a mesh surface), this samples the
// surface of the Earth: uniform-on-sphere candidate lon/lat, kept when inside a
// land polygon, then projected with the SAME lonLatToVec3 the live pins use so
// continents and pins share one coordinate frame.
//
// Usage: node scripts/globe-to-ply.mjs <land.geojson> <output.ply> [pointCount]
//   pointCount is optional and defaults to 50000 (the renderer's default count).

import fs from "node:fs";
import { lonLatToVec3 } from "../src/lib/geo.js";

const [, , inPath, outPath, countArg] = process.argv;
if (!inPath || !outPath) {
  console.error("usage: node scripts/globe-to-ply.mjs <land.geojson> <output.ply> [pointCount]");
  process.exit(1);
}

const POINTS = countArg ? parseInt(countArg, 10) : 50000;
if (!Number.isInteger(POINTS) || POINTS <= 0) {
  console.error("pointCount must be a positive integer, got:", countArg);
  process.exit(1);
}

// --- Load land polygons -----------------------------------------------------
// Flatten the FeatureCollection into a list of { outer, holes, bbox } where a
// ring is [[lon,lat], ...]. bbox = [minLon, minLat, maxLon, maxLat] of the
// outer ring, used to skip polygons a candidate can't possibly be inside.
const geo = JSON.parse(fs.readFileSync(inPath, "utf8"));

/** @type {{outer:number[][], holes:number[][][], bbox:number[]}[]} */
const polys = [];

function addPolygon(rings) {
  if (!rings.length) return;
  const outer = rings[0];
  const holes = rings.slice(1);
  let minLon = Infinity, minLat = Infinity, maxLon = -Infinity, maxLat = -Infinity;
  for (const [lon, lat] of outer) {
    if (lon < minLon) minLon = lon;
    if (lon > maxLon) maxLon = lon;
    if (lat < minLat) minLat = lat;
    if (lat > maxLat) maxLat = lat;
  }
  polys.push({ outer, holes, bbox: [minLon, minLat, maxLon, maxLat] });
}

for (const f of geo.features ?? []) {
  const g = f.geometry;
  if (!g) continue;
  if (g.type === "Polygon") addPolygon(g.coordinates);
  else if (g.type === "MultiPolygon") for (const p of g.coordinates) addPolygon(p);
}
if (!polys.length) {
  console.error("no land polygons found in", inPath);
  process.exit(1);
}

// Ray-casting point-in-ring test on the lon/lat plane.
function inRing(lon, lat, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0], yi = ring[i][1];
    const xj = ring[j][0], yj = ring[j][1];
    const intersect =
      yi > lat !== yj > lat &&
      lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi;
    if (intersect) inside = !inside;
  }
  return inside;
}

function onLand(lon, lat) {
  for (const { outer, holes, bbox } of polys) {
    if (lon < bbox[0] || lon > bbox[2] || lat < bbox[1] || lat > bbox[3]) continue;
    if (!inRing(lon, lat, outer)) continue;
    let hole = false;
    for (const h of holes) if (inRing(lon, lat, h)) { hole = true; break; }
    if (!hole) return true;
  }
  return false;
}

// --- Sample -----------------------------------------------------------------
// Equal-area sampling on the sphere: z uniform in [-1,1] → lat = asin(z); lon
// uniform. This gives even stipple density across the globe rather than the
// pole-bunching of a naive lat/lon grid.
const xyz = new Float32Array(POINTS * 3);
let written = 0;
let tries = 0;
const DEG = 180 / Math.PI;
while (written < POINTS) {
  tries++;
  const lon = Math.random() * 360 - 180;
  const lat = Math.asin(Math.random() * 2 - 1) * DEG;
  if (!onLand(lon, lat)) continue;
  const [x, y, z] = lonLatToVec3(lon, lat, 0.5);
  xyz[written * 3] = x;
  xyz[written * 3 + 1] = y;
  xyz[written * 3 + 2] = z;
  written++;
}

// --- Write binary PLY (12 bytes xyz float + 4 bytes rgba uchar per vertex) ---
const header =
  "ply\n" +
  "format binary_little_endian 1.0\n" +
  "comment generated by scripts/globe-to-ply.mjs (Natural Earth land sample)\n" +
  `element vertex ${POINTS}\n` +
  "property float x\nproperty float y\nproperty float z\n" +
  "property uchar red\nproperty uchar green\nproperty uchar blue\nproperty uchar alpha\n" +
  "end_header\n";
const headerBuf = Buffer.from(header, "latin1");
const body = Buffer.alloc(POINTS * 16);
for (let i = 0; i < POINTS; i++) {
  const o = i * 16;
  body.writeFloatLE(xyz[i * 3], o);
  body.writeFloatLE(xyz[i * 3 + 1], o + 4);
  body.writeFloatLE(xyz[i * 3 + 2], o + 8);
  body[o + 12] = 255; body[o + 13] = 255; body[o + 14] = 255; body[o + 15] = 255;
}
fs.writeFileSync(outPath, Buffer.concat([headerBuf, body]));
console.log(
  `${inPath} -> ${outPath}  (${POINTS} pts, ${(tries / POINTS).toFixed(2)} samples/pt, land hit-rate ${((POINTS / tries) * 100).toFixed(0)}%)`,
);
